# Generated by Django 2.0b1 on 2017-11-07 16:14

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import measurements.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_on_trillian', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID on Trillian')),
                ('callback_auth_code', models.CharField(default=measurements.utils.generate_random_token, max_length=50,
                                                        verbose_name='callback auth code')),
                ('requested', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='requested')),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='started')),
                ('finished', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='finished')),
                ('dns_results', django.contrib.postgres.fields.ArrayField(
                    base_field=models.GenericIPAddressField(), blank=True, default=list, size=None,
                    verbose_name='DNS results')),
            ],
            options={
                'verbose_name': 'instance',
                'verbose_name_plural': 'instances',
            },
        ),
        migrations.CreateModel(
            name='InstanceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('web_response', django.contrib.postgres.fields.jsonb.JSONField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.Instance',
                                               verbose_name='instance')),
                ('marvin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instances.Marvin',
                                             verbose_name='Marvin')),
            ],
            options={
                'verbose_name': 'instance result',
                'verbose_name_plural': 'instance results',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('url', models.URLField(db_index=True, verbose_name='URL')),
                ('time', models.TimeField(verbose_name='time')),
                ('start', models.DateField(verbose_name='start')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end')),
                ('frequency', models.CharField(choices=[
                    ('D', 'Every day'),
                    ('W', 'Every week'),
                    ('M', 'Every month')
                ], max_length=1, verbose_name='frequency')),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                            verbose_name='owner')),
                ('trillians', models.ManyToManyField(to='instances.Trillian', verbose_name='Trillians')),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, verbose_name='URL')),
                ('requested', models.DateTimeField(db_index=True, verbose_name='requested')),
                ('started', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='started')),
                ('finished', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='finished')),
                ('is_public', models.BooleanField(default=True, verbose_name='is_public')),
                ('image_score', models.FloatField(blank=True, db_index=True, null=True, verbose_name='image score')),
                ('resource_score', models.FloatField(blank=True, db_index=True, null=True,
                                                     verbose_name='resource score')),
                ('overall_score', models.FloatField(blank=True, db_index=True, null=True,
                                                    verbose_name='overall score')),
                ('feedback_category', models.PositiveSmallIntegerField(blank=True, choices=[
                    (1, 'Error'),
                    (5, 'Warning'),
                    (10, 'Good')
                ], null=True, verbose_name='feedback category')),
                ('feedback_text', models.TextField(blank=True, verbose_name='feedback text')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                            to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                               to='measurements.Schedule', verbose_name='schedule')),
            ],
            options={
                'verbose_name': 'test run',
                'verbose_name_plural': 'test runs',
            },
        ),
        migrations.AddField(
            model_name='instance',
            name='testrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurements.TestRun',
                                    verbose_name='test run'),
        ),
        migrations.AddField(
            model_name='instance',
            name='trillian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instances.Trillian',
                                    verbose_name='Trillian'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('testrun', 'trillian')},
        ),
    ]
