# Generated by Django 2.0b1 on 2017-11-18 23:20

import django.utils.datetime_safe
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instancerunresult',
            old_name='instance',
            new_name='instancerun',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.DateField(blank=True, help_text='The last day that you want the tests to be run', null=True,
                                   verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('D', 'Every day'), ('W', 'Every week'), ('M', 'Every month')],
                                   help_text='Frequency to schedule the tests. '
                                             'Can be "D" (daily), "W" (weekly) or "M" (monthly)',
                                   max_length=1, verbose_name='frequency'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether the test results should be publicly visible',
                                      verbose_name='is public'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(help_text='Name your test schedule, must be unique', max_length=100,
                                   verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateField(default=django.utils.datetime_safe.date.today,
                                   help_text='The first day that you want the tests to be run', verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(help_text='The time of day in UTC when you want the tests to be scheduled',
                                   verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trillians',
            field=models.ManyToManyField(help_text='The data centres from where you want this URL to be tested',
                                         to='instances.Trillian', verbose_name='Trillians'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='url',
            field=models.URLField(db_index=True, help_text='The URL you want to test', verbose_name='URL'),
        ),
    ]
