# Generated by Django 2.0b1 on 2017-11-19 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0002_help_texts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('start', 'end'), 'verbose_name': 'schedule', 'verbose_name_plural': 'schedules'},
        ),
    ]
