# Generated by Django 2.0.7 on 2018-07-10 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0004_add_analysed_ts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancerun',
            options={
                'permissions': (
                    ('report_back', 'Report back on progress'),
                ),
                'verbose_name': 'instance run',
                'verbose_name_plural': 'instance runs'
            },
        ),
    ]
