# Generated by Django 2.0rc1 on 2017-11-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0004_related_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancerun',
            name='testrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instanceruns',
                                    to='measurements.TestRun', verbose_name='test run'),
        ),
    ]
