# Generated by Django 2.0rc1 on 2017-12-13 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0006_other_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancerunmessage',
            name='instancerun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                    to='measurements.InstanceRun', verbose_name='instance run'),
        ),
        migrations.AlterField(
            model_name='instancerunmessage',
            name='message',
            field=models.CharField(max_length=200, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='instancerunresult',
            name='instancerun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results',
                                    to='measurements.InstanceRun', verbose_name='instance run'),
        ),
        migrations.AlterField(
            model_name='testrunmessage',
            name='message',
            field=models.CharField(max_length=200, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='testrunmessage',
            name='testrun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                    to='measurements.TestRun', verbose_name='test run'),
        ),
    ]
