# Generated by Django 2.0.7 on 2018-07-15 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0006_remove_instancerun_callback_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancerunresult',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
