# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0007_instancerunresult_when'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancerun',
            name='id_on_trillian',
        ),
        migrations.AddField(
            model_name='instancerun',
            name='trillian_url',
            field=models.URLField(default='', verbose_name='Trillian URL'),
            preserve_default=False,
        ),
    ]
