# Generated by Django 2.0.7 on 2018-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0008_trillian_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancerun',
            name='trillian_url',
            field=models.URLField(blank=True, verbose_name='Trillian URL'),
        ),
    ]
