# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0009_auto_20180716_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancerunmessage',
            name='source',
            field=models.CharField(
                choices=[
                    ('L', 'Local'),
                    ('T', 'Trillian')
                ],
                default='L',
                max_length=1,
                verbose_name='source'
            ),
        ),
    ]
