# Generated by Django 2.0.7 on 2018-07-23 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0010_instancerunmessage_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ('requested',), 'verbose_name': 'test run', 'verbose_name_plural': 'test runs'},
        ),
    ]
