# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-23 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0010_instancerunmessage_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testrun',
            options={'ordering': ('requested',), 'verbose_name': 'test run', 'verbose_name_plural': 'test runs'},
        ),
    ]
