# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD 3-Clause License. Please seel the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-11-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0012_instancerunresult_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunAverage',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')
                 ),
                ('instance_type', models.CharField(
                    choices=[
                        ('dual-stack', 'Dual-stack'),
                        ('v4only', 'IPv4-only'),
                        ('v6only', 'IPv6-only'),
                        ('nat64', 'IPv6 with NAT64')
                    ],
                    max_length=10,
                    verbose_name='instance type')
                 ),
                ('image_score', models.FloatField(
                    blank=True,
                    db_index=True,
                    null=True,
                    verbose_name='image score')
                 ),
                ('resource_score', models.FloatField(
                    blank=True,
                    db_index=True,
                    null=True,
                    verbose_name='resource score')
                 ),
                ('overall_score', models.FloatField(
                    blank=True,
                    db_index=True,
                    null=True,
                    verbose_name='overall score')
                 ),
                ('testrun', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='averages',
                    to='measurements.TestRun',
                    verbose_name='test run')
                 ),
            ],
            options={
                'verbose_name': 'test run average',
                'verbose_name_plural': 'test run averages',
                'ordering': ('testrun', 'instance_type'),
            },
        ),
    ]
