# Generated by Django 2.0b1 on 2017-11-18 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marvin',
            options={'ordering': ('trillian', 'name',)},
        ),
    ]
