# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trillian',
            name='token',
            field=models.CharField(
                default='',
                max_length=40,
                verbose_name='token'),
            preserve_default=False,
        ),
    ]
