# Generated by Django 2.0.7 on 2018-07-15 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0002_trillian_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvin',
            name='alive',
        ),
    ]
