# Generated by Django 2.0b1 on 2017-11-19 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0002_marvin_ordering'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marvin',
            unique_together=set(),
        ),
    ]
