# Generated by Django 2.0rc1 on 2017-11-19 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0003_marvin_uniqueness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvin',
            name='trillian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marvins',
                                    to='instances.Trillian', verbose_name='Trillian'),
        ),
    ]
