# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
#  Copyright (c) 2018, S.J.M. Steffann. This software is licensed under the BSD
#  3-Clause License. Please see the LICENSE file in the project root directory.
# ••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••

# Generated by Django 2.0.7 on 2018-07-15 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0003_remove_marvin_alive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trillian',
            old_name='alive',
            new_name='is_alive',
        ),
    ]
