# Generated by Django 2.0rc1 on 2017-11-25 19:50

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instances', '0004_related_marvins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trillian',
            name='country',
            field=django_countries.fields.CountryField(db_index=True, max_length=2, verbose_name='country'),
        ),
    ]
